# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/protobuf/any.proto\"-\n\x0b\x45\x63hoRequest\x12\x1e\n\x07payload\x18\x01 \x01(\x0b\x32\r.echo.Payload\"\\\n\tEchoReply\x12\x1e\n\x07payload\x18\x01 \x01(\x0b\x32\r.echo.Payload\x12/\n\x0breceived_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8f\x04\n\x07Payload\x12\x0b\n\x03i32\x18\x01 \x01(\x05\x12\x0b\n\x03i64\x18\x02 \x01(\x03\x12\x0b\n\x03u32\x18\x03 \x01(\r\x12\x0b\n\x03u64\x18\x04 \x01(\x04\x12\x0b\n\x03s32\x18\x05 \x01(\x11\x12\x0b\n\x03s64\x18\x06 \x01(\x12\x12\x0c\n\x04\x66lag\x18\x07 \x01(\x08\x12\x1a\n\x05\x63olor\x18\x08 \x01(\x0e\x32\x0b.echo.Color\x12\x0b\n\x03\x66\x36\x34\x18\t \x01(\x06\x12\x0c\n\x04sf64\x18\n \x01(\x10\x12\t\n\x01\x64\x18\x0b \x01(\x01\x12\x0c\n\x04text\x18\x0c \x01(\t\x12\x0c\n\x04\x62lob\x18\r \x01(\x0c\x12\x1c\n\x06nested\x18\x0e \x01(\x0b\x32\x0c.echo.Nested\x12\x0b\n\x03\x66\x33\x32\x18\x0f \x01(\x07\x12\x0c\n\x04sf32\x18\x10 \x01(\x0f\x12\n\n\x02\x66l\x18\x11 \x01(\x02\x12\x13\n\x0bpacked_ints\x18\x12 \x03(\x05\x12\x0f\n\x07strings\x18\x13 \x03(\t\x12\x15\n\x0b\x63hoice_text\x18\x14 \x01(\tH\x00\x12\x14\n\nchoice_int\x18\x15 \x01(\x05H\x00\x12%\n\x04tags\x18\x16 \x03(\x0b\x32\x17.echo.Payload.TagsEntry\x12+\n\x08\x64uration\x18\x17 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\'\n\tany_field\x18\x18 \x01(\x0b\x32\x14.google.protobuf.Any\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x08\n\x06\x63hoice\"&\n\x06Nested\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05*<\n\x05\x43olor\x12\x15\n\x11\x43OLOR_UNSPECIFIED\x10\x00\x12\x07\n\x03RED\x10\x01\x12\t\n\x05GREEN\x10\x02\x12\x08\n\x04\x42LUE\x10\x03\x32\x32\n\x04\x45\x63ho\x12*\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x0f.echo.EchoReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOAD_TAGSENTRY']._loaded_options = None
  _globals['_PAYLOAD_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_COLOR']._serialized_start=823
  _globals['_COLOR']._serialized_end=883
  _globals['_ECHOREQUEST']._serialized_start=112
  _globals['_ECHOREQUEST']._serialized_end=157
  _globals['_ECHOREPLY']._serialized_start=159
  _globals['_ECHOREPLY']._serialized_end=251
  _globals['_PAYLOAD']._serialized_start=254
  _globals['_PAYLOAD']._serialized_end=781
  _globals['_PAYLOAD_TAGSENTRY']._serialized_start=728
  _globals['_PAYLOAD_TAGSENTRY']._serialized_end=771
  _globals['_NESTED']._serialized_start=783
  _globals['_NESTED']._serialized_end=821
  _globals['_ECHO']._serialized_start=885
  _globals['_ECHO']._serialized_end=935
# @@protoc_insertion_point(module_scope)
