# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import operation_pb2 as operation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in operation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationServiceStub(object):
    """A tiny math service used to exercise gRPC's "rich" error model:
    a MULTIPLY request is deliberately rejected with google.rpc.Status
    carrying an ErrorInfo detail via the `grpc-status-details-bin` trailer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/operation.OperationService/Compute',
                request_serializer=operation__pb2.OperationRequest.SerializeToString,
                response_deserializer=operation__pb2.OperationReply.FromString,
                _registered_method=True)


class OperationServiceServicer(object):
    """A tiny math service used to exercise gRPC's "rich" error model:
    a MULTIPLY request is deliberately rejected with google.rpc.Status
    carrying an ErrorInfo detail via the `grpc-status-details-bin` trailer.
    """

    def Compute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=operation__pb2.OperationRequest.FromString,
                    response_serializer=operation__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operation.OperationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('operation.OperationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationService(object):
    """A tiny math service used to exercise gRPC's "rich" error model:
    a MULTIPLY request is deliberately rejected with google.rpc.Status
    carrying an ErrorInfo detail via the `grpc-status-details-bin` trailer.
    """

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.OperationService/Compute',
            operation__pb2.OperationRequest.SerializeToString,
            operation__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
