# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: operation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foperation.proto\x12\toperation\"Q\n\x10OperationRequest\x12+\n\toperation\x18\x01 \x01(\x0e\x32\x18.operation.OperationType\x12\x10\n\x08operands\x18\x02 \x03(\x03\" \n\x0eOperationReply\x12\x0e\n\x06result\x18\x01 \x01(\x03*F\n\rOperationType\x12\x1e\n\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x32U\n\x10OperationService\x12\x41\n\x07\x43ompute\x12\x1b.operation.OperationRequest\x1a\x19.operation.OperationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONTYPE']._serialized_start=147
  _globals['_OPERATIONTYPE']._serialized_end=217
  _globals['_OPERATIONREQUEST']._serialized_start=30
  _globals['_OPERATIONREQUEST']._serialized_end=111
  _globals['_OPERATIONREPLY']._serialized_start=113
  _globals['_OPERATIONREPLY']._serialized_end=145
  _globals['_OPERATIONSERVICE']._serialized_start=219
  _globals['_OPERATIONSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
